### ISSUE TITLE
Temp showing as -127 in NT MODE

### ISSUE THREAD

**Issue by projectcobalt** [terciops/Paladin-692#1]
When in NT MODE eventually "SENSOR" is replaced with -127 temp retriggering constant health top ups

**Comment by terciops** [comment]
Power the Paladin OFF - pause = ON.  If that does not resolve the problem, or the temperature is not correctly displayed, you will need a replacement temperature probe.  Let me know with an address, I will send you one.

**Comment by projectcobalt** [comment]
Appreciate that, although I'm running explicitly in NT MODE and have no temp probe connected. Using the unit thermostat as the backstop... would love to go the lora route as I have some radio modules at home that could be used.... have been resetting the unit once it errors but sometimes time escapes and a forced health occurs which it never exits.... thought I would do some dev and provide feedback :)

**Comment by terciops** [comment]
OK I understand.   What version of firmware are you running?  I will check the code and see why that NO MODE is not suppressing the Legionaire's countdown.

**Comment by projectcobalt** [comment]
On the latest 693

**Comment by terciops** [comment]
OK - many thanks for that feedback.  Tricky little bug...
In 69x I introduced a reboot of the temperature probe to force a reset of the temp circuit if the system went to NT MODE for whatever reason.   This was effective on testing and a temp probe could be removed and replaced in run mode and would restart correctly without a reboot.  Nice.  But,  this method was not correctly resetting the NOTEMP flag until later and allowed the Legionnaire's counter to continue to run.  Hence the top ups once that counter reached the 168 hours (V693).  
Without a valid temperature, there was no way the system would remove the Legionnaire's flag.

Fixes :  Stopped the Legionnaire's counter incrementing when in NT MODE
            Replaced a -127C result with 0C for neatness.

V693 recompiled with these fixes and the revised binary is V693NT for now.

I would appreciate feedback if this solves the issue.

Ref the LoRa.   The ESP32 core firmware has recently been totally upgraded and has broken some libraries that the LoRa uses.  However, I will have time to work on that later this month and it will get sorted.  Then I can think about the LoRa modules again.  It sounds like you need the Remote Temperature module.   The RT unit is USB powered, do you have a separate mains outlet near your tank to use a USB adaptor?
